name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64] 
    
    env:
      TARGET_SERVER: "chatapp@10.0.3.11"
      APP_DIR: "/new_chatapp"
      APP_SUBDIR: "fundoo"
      VENV_DIR: "$APP_DIR/venv"

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Sync code to backend server using rsync
      - name: Sync application code to backend server
        run: |
          echo "Syncing application code to $TARGET_SERVER..."
          rsync -avz --exclude '.git' ./ $TARGET_SERVER:$APP_DIR

      # Step 3: Build and deploy the application
      - name: Build and deploy application
        run: |
          echo "Building and deploying application..."
          ssh $TARGET_SERVER << EOF
              set -e

              cd $APP_DIR

              # Activate virtual environment and install dependencies
              source $VENV_DIR/bin/activate
              pip install -r requirements.txt

              # Run database migrations
              cd $APP_SUBDIR
              python3 manage.py makemigrations
              bash ~/run_migrate.sh

              # Restart Django service
              sudo systemctl restart django.service
              sudo systemctl status django.service
          EOF
          
      - name: Notify success
        run: echo "CI/CD pipeline completed successfully!"
